[package]
name = "simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.33"
rand = "0.10.2"
tokio = { version = "1.40", features = [
    "rt",
    "time",
    "test-util",
    "macros",
]}
three-d = { version = "0.19", features = ["egui-gui"] }
three-d-asset = "0.10"
postcard = { version = "1.0", features = ["alloc"] }
crc = "3.0"
cobs = "0.2"
serde = { version = "1.0", features = ["derive"] }
