/* Bootloader memory aliases - references unified memory.x at workspace root */
INCLUDE unified_memory.x

REGION_ALIAS("CODE", BOOTLOADER_FLASH);
REGION_ALIAS("USR", BOOTLOADER_USR);

REGION_ALIAS("FLASH", CODE);

REGION_ALIAS("REGION_TEXT", CODE);
REGION_ALIAS("REGION_RODATA", CODE);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
