MEMORY
{
    /* Bootloader occupies first 32K of flash */
    CODE   (rx)  : ORIGIN = 0x00000000, LENGTH =  16K
    USR    (rwx) : ORIGIN = 0x08000000, LENGTH =  16K
    SYS    (rwx) : ORIGIN = 0x1FFF8000, LENGTH =   28K
    VND    (r)   : ORIGIN = 0x1FFFF700, LENGTH =   256
    OPT    (rw)  : ORIGIN = 0x1FFFF800, LENGTH =   128
    RAM    (rwx) : ORIGIN = 0x20000000, LENGTH =   20K
}

REGION_ALIAS("FLASH", CODE);

REGION_ALIAS("REGION_TEXT", CODE);
REGION_ALIAS("REGION_RODATA", CODE);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
