[package]
name = "proto"
version = "0.1.0"
edition = "2024"

[dependencies]
trickle = { path = "../trickle", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = { version = "1.0", features = ["use-crc"] }
cobs = { version = "0.3", default-features = false }
crc = "3.4"
embassy-time = { version = "0.5", optional = true }
heapless = { version = "0.9", features = ["serde"] }

[features]
default = ["app", "bl", "std"]
app = []
bl = []
std = ["serde/std"]
embassy = ["embassy-time"]
