[package]
name = "kelp-app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kelp-app"
path = "src/main.rs"

[dependencies]
hal = { path = "../hal" }
qingke-rt = { version = "0.7", features = ["v4"] }
embassy-executor = { version = "0.10.0", features = ["platform-spin", "executor-thread"] }
embassy-time = { version = "0.5.1", features = ["generic-queue-8"] }
fring = { version = "0.5", features = ["portable-atomic"] }

[profile.release]
strip = false   # symbols are not flashed to the microcontroller, so don't strip them.
lto = true
opt-level = 3

[profile.dev]
strip = false
lto = true
opt-level = 2
