[package]
name = "kelp-app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kelp-app"
path = "src/main.rs"

[dependencies]
hal = { path = "../hal" }
qingke-rt = { version = "0.7", features = ["v4"] }
embassy-executor = { version = "0.10.0", features = ["platform-spin", "executor-thread"] }
embassy-time = { version = "0.5.1", features = ["generic-queue-8"] }
embassy-sync = { version = "0.8" }
embassy-futures = "0.1"
fring = { version = "0.5", features = ["portable-atomic"] }
heapless = "0.9"
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = { version = "1.0", features = ["use-crc"] }
cobs = { version = "0.3", default-features = false }
crc = "3.4"
static_cell = "2.1"
oorandom = "11.1.5"
riscv = "0.12" # XXX

[profile.release]
strip = false   # symbols are not flashed to the microcontroller, so don't strip them.
lto = true
opt-level = 3

[profile.dev]
strip = false
lto = true
opt-level = 2
